_class = [_this,0,"",[""]] call BIS_fnc_param;
_obj = [_this,1,player,[objNull]] call BIS_fnc_param;
_isJIP = [_this,2,false,[true]] call BIS_fnc_param;

if (_class == "") exitWith {};
_class = toUpper _class;

#define this _obj
// --- Ab hier bearbeiten:

if (_class == "CO") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_Beret_Colonel";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierSpec_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "11Rnd_45ACP_Mag";
	this addItemToVest "SmokeShellOrange";
	this addItemToVest "SmokeShellBlue";
	this addItemToVest "SmokeShellPurple";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_Pistol_heavy_01_F";
	this addPrimaryWeaponItem "optic_Aco";
	this addHandgunItem "optic_MRD";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "XO") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_MilCap_mcamo";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierSpec_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "11Rnd_45ACP_Mag";
	this addItemToVest "SmokeShellOrange";
	this addItemToVest "SmokeShellBlue";
	this addItemToVest "SmokeShellPurple";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_Pistol_heavy_01_F";
	this addPrimaryWeaponItem "optic_Aco";
	this addHandgunItem "optic_MRD";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "OFFICER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_Beret_blk";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierSpec_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "11Rnd_45ACP_Mag";
	this addItemToVest "SmokeShellOrange";
	this addItemToVest "SmokeShellBlue";
	this addItemToVest "SmokeShellPurple";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_Pistol_heavy_01_F";
	this addPrimaryWeaponItem "optic_Aco";
	this addHandgunItem "optic_MRD";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "MIO") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemLAPTOP_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_Beret_blk";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierSpec_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "11Rnd_45ACP_Mag";
	this addItemToVest "SmokeShellOrange";
	this addItemToVest "SmokeShellBlue";
	this addItemToVest "SmokeShellPurple";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_Pistol_heavy_01_F";
	this addPrimaryWeaponItem "optic_Aco";
	this addHandgunItem "optic_MRD";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "JTAC") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Laserdesignator";
	this addHeadgear "H_HelmetB_light_black";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 6 do { this addItemToVest "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 8 do { this addItemToVest "1Rnd_SmokeRed_Grenade_shell" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToBackpack "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToBackpack "1Rnd_SmokeOrange_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToBackpack "1Rnd_SmokePurple_Grenade_shell" };
	this addMagazine "Laserbatteries";
	this addWeapon "arifle_MX_GL_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShellGreen" };
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellGreen" };
	for "_i" from 1 to 2 do { this addItemToVest "B_IR_Grenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "UAV OPERATOR") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "B_UavTerminal";
	this addWeapon "Rangefinder";
	this addHeadgear "H_HelmetB_light";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierSpec_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";
	this addBackpack "B_UAV_01_backpack_F";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "MEDIC") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetB_light";
	this addUniform "U_B_CombatUniform_mcam_tshirt";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 4 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "SmokeShellBlue";
	this addItemToVest "SmokeShellOrange";
	this addItemToVest "B_IR_Grenade";

	[this,true] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "SQUADLEADER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_HelmetSpecB_paint1";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierGL_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 6 do { this addItemToVest "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeGreen_Grenade_shell" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell" };
	this addWeapon "arifle_MX_GL_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "FIRETEAMLEADER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_PlateCarrierGL_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeGreen_Grenade_shell" };
	for "_i" from 1 to 6 do { this addItemToVest "1Rnd_HE_Grenade_shell" };
	this addWeapon "arifle_MX_GL_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";
	this addBackpack "B_AssaultPack_rgr";
	for "_i" from 1 to 3 do { this addItemToBackpack "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 3 do { this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "AUTORIFLEMAN") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam_tshirt";
	this addVest "V_PlateCarrier1_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "100Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 2 do { this addItemToVest "100Rnd_65x39_caseless_mag" };
	this addItemToUniform "100Rnd_65x39_caseless_mag";
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MX_SW_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addBackpack "B_AssaultPack_rgr";
	for "_i" from 1 to 2 do { this addItemToBackpack "100Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 2 do { this addItemToBackpack "100Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "ASSISTANT AUTORIFLEMAN") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_AssaultPack_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 3 do { this addItemToBackpack "100Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 3 do { this addItemToBackpack "100Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "GRENADIER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrierGL_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeGreen_Grenade_shell" };
	for "_i" from 1 to 6 do { this addItemToVest "1Rnd_HE_Grenade_shell" };
	this addWeapon "arifle_MX_GL_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addBackpack "B_AssaultPack_rgr";
	for "_i" from 1 to 3 do { this addItemToBackpack "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 3 do { this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "RIFLEMAN") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 4 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 4 do { this addItemToBackpack "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShellRed" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShellGreen" };
	for "_i" from 1 to 2 do { this addItemToBackpack "100Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 2 do { this addItemToBackpack "100Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 8 do { this addItemToBackpack "1Rnd_HE_Grenade_shell" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "RIFLEMAN (AT)") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addBackpack "B_AssaultPack_rgr";
	for "_i" from 1 to 2 do { this addItemToBackpack "NLAW_F" };
	this addWeapon "launch_NLAW_F";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "ASSISTANT RIFLEMAN (AT)") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 2 do { this addItemToBackpack "NLAW_F" };
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "EXPLOSIVE SPECIALIST") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_Carryall_oli";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addItemToBackpack "MineDetector";
	this addItemToBackpack "Toolkit";
	for "_i" from 1 to 2 do { this addItemToBackpack "DemoCharge_Remote_Mag" };
	this addItemToBackpack "SatchelCharge_Remote_Mag";
	for "_i" from 1 to 2 do { this addItemToBackpack "APERSBoundingMine_Range_Mag" };
	for "_i" from 1 to 2 do { this addItemToBackpack "APERSTripMine_Wire_Mag" };
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "COMBAT MEDIC") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam_tshirt";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToBackpack "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 2 do { this addItemToBackpack "100Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 2 do { this addItemToBackpack "100Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,true] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "DESIGNATED MARKSMAN") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	for "_i" from 1 to 5 do { this addItemToVest "20Rnd_762x51_Mag" };
	for "_i" from 1 to 3 do { this addItemToUniform "20Rnd_762x51_Mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "srifle_EBR_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_DMS";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addBackpack "B_AssaultPack_rgr";
	for "_i" from 1 to 8 do { this addItemToBackpack "20Rnd_762x51_Mag" };
	for "_i" from 1 to 2 do { this addItemToBackpack "SmokeShell" };
	this addItemToBackpack "SmokeShellRed";
	this addItemToBackpack "SmokeShellGreen";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "AT SPECIALIST") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam_tshirt";
	this addVest "V_PlateCarrier1_rgr";
	for "_i" from 1 to 7 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 3 do { this addItemToUniform "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 2 do { this addItemToBackpack "Titan_AT" };
	this addItemToBackpack "Titan_AP";
	this addWeapon "launch_B_Titan_short_F";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "ASSISTANT AT") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToBackpack "Titan_AT" };
	this addItemToBackpack "Titan_AP";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "AA SPECIALIST") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam_tshirt";
	this addVest "V_PlateCarrier1_rgr";
	for "_i" from 1 to 7 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 3 do { this addItemToUniform "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "Titan_AA";
	this addBackpack "B_AssaultPack_rgr";
	this addItemToBackpack "Titan_AA";
	this addWeapon "launch_B_Titan_F";
	this addItemToBackpack "Titan_AA";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "ASSISTANT AA") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Rangefinder";
	this addHeadgear "H_HelmetB";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_PlateCarrier1_rgr";
	this addBackpack "B_Kitbag_mcamo";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 5 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToBackpack "Titan_AA" };
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Hamr";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "HandGrenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "SNIPER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Laserdesignator";
	this addUniform "U_B_GhillieSuit";
	this addVest "V_Chestrig_rgr";
	this addItemToVest "cse_ab_Kestrel4500";
	this addItemToVest "cse_ab_ATragMX";
	for "_i" from 1 to 7 do { this addItemToVest "7Rnd_408_Mag" };
	for "_i" from 1 to 3 do { this addItemToVest "16Rnd_9x21_Mag" };
	this addMagazine "Laserbatteries";
	(UniformContainer this) addItemCargoGlobal ["optic_Nightstalker",1];
	this addWeapon "srifle_LRR_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_SOS";
	this addHandgunItem "muzzle_snds_L";
	for "_i" from 1 to 3 do { this addItemToUniform "7Rnd_408_Mag" };
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShell" };
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellRed" };
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellGreen" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", true, true];
};
if (_class == "SPOTTER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "B_UavTerminal";
	this addWeapon "Laserdesignator";
	this addUniform "U_B_GhillieSuit";
	this addVest "V_Chestrig_rgr";
	this addBackpack "tf_rt1523g_big";
	this addItemToVest "cse_ab_Kestrel4500";
	this addItemToVest "cse_ab_ATragMX";
	for "_i" from 1 to 8 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 4 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToBackpack "7Rnd_408_Mag" };
	this addMagazine "Laserbatteries";
	(UniformContainer this) addItemCargoGlobal ["optic_Nightstalker",1];
	this addWeapon "arifle_MXM_F";
	this addWeapon "hgun_P07_F";
	this addHandgunItem "muzzle_snds_L";
	this addPrimaryWeaponItem "acc_pointer_IR";
	this addPrimaryWeaponItem "optic_DMS";
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShell" };
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellRed" };
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellGreen" };
	for "_i" from 1 to 3 do { this addItemToUniform "16Rnd_9x21_Mag" };
	this addItemToUniform "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", true, true];
};
if (_class == "RECON TEAMLEADER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Laserdesignator";
	this addHeadgear "H_Watchcap_blk";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_Chestrig_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 6 do { this addItemToVest "1Rnd_HE_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeRed_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeGreen_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokeOrange_Grenade_shell" };
	for "_i" from 1 to 2 do { this addItemToVest "1Rnd_SmokePurple_Grenade_shell" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addMagazine "Laserbatteries";
	this addItemToBackpack "optic_Hamr";
	this addItemToBackpack "muzzle_snds_H";
	this addWeapon "arifle_MX_GL_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Nightstalker";
	this addHandgunItem "muzzle_snds_L";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "B_IR_Grenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "RECON SCOUT") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Laserdesignator";
	this addHeadgear "H_Watchcap_blk";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_Chestrig_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addMagazine "Laserbatteries";
	this addItemToVest "optic_Hamr";
	this addItemToVest "muzzle_snds_H";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Nightstalker";
	this addHandgunItem "muzzle_snds_L";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "B_IR_Grenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "RECON UAV OPERATOR") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "B_UavTerminal";
	this addWeapon "Laserdesignator";
	this addHeadgear "H_Watchcap_blk";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_Chestrig_rgr";
	this addBackpack "B_UAV_01_backpack_F";
	for "_i" from 1 to 3 do { this addItemToVest "30Rnd_65x39_caseless_mag_Tracer" };
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addMagazine "Laserbatteries";
	this addItemToVest "optic_Hamr";
	this addItemToVest "muzzle_snds_H";
	this addWeapon "arifle_MX_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Nightstalker";
	this addHandgunItem "muzzle_snds_L";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "B_IR_Grenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "RECON MARKSMAN") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Laserdesignator";
	this addHeadgear "H_Watchcap_blk";
	this addUniform "U_B_CombatUniform_mcam_vest";
	this addVest "V_Chestrig_rgr";
	for "_i" from 1 to 3 do { this addItemToVest "20Rnd_762x51_Mag" };
	for "_i" from 1 to 3 do { this addItemToUniform "20Rnd_762x51_Mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addMagazine "Laserbatteries";
	this addItemToVest "optic_Nightstalker";
	this addItemToVest "muzzle_snds_B";
	this addWeapon "srifle_EBR_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_DMS";
	this addHandgunItem "muzzle_snds_L";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { this addItemToVest "B_IR_Grenade" };
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "COMMANDER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetCrew_B";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_BandollierB_rgr";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Holosight";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "CREW") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_HelmetCrew_B";
	this addUniform "U_B_CombatUniform_mcam";
	this addVest "V_BandollierB_rgr";
	this addBackpack "B_FieldPack_cbr";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Holosight";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "HELIPILOT") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_PilotHelmetHeli_B";
	this addUniform "U_B_HeliPilotCoveralls";
	this addVest "V_TacVest_blk";
	this addBackpack "tf_rt1523g_black";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	this addWeapon "arifle_MXC_Black_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "HELICREW") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "Binocular";
	this addHeadgear "H_CrewHelmetHeli_B";
	this addUniform "U_B_HeliPilotCoveralls";
	this addVest "V_TacVest_blk";
	this addBackpack "tf_rt1523g_big";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	for "_i" from 1 to 2 do { this addItemToVest "30Rnd_65x39_caseless_mag" };
	this addItemToVest "16Rnd_9x21_Mag";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellOrange" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellBlue" };
	this addWeapon "arifle_MXC_Black_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShell" };
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	this addItemToVest "HandGrenade";
	for "_i" from 1 to 2 do { this addItemToVest "MiniGrenade" };
	this addItemToVest "B_IR_Grenade";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "JETPILOT") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addHeadgear "H_PilotHelmetFighter_B";
	this addUniform "U_B_PilotCoveralls";
	this addBackpack "B_Parachute";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_45ACP_Mag_SMG_01_Tracer_Green" };
	this addItemToUniform "16Rnd_9x21_Mag";
	this addWeapon "SMG_01_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Holosight_smg";
	this addItemToUniform "SmokeShellRed";
	this addItemToUniform "SmokeShellGreen";
	for "_i" from 1 to 2 do { _obj addItemToUniform "cse_bandage_basic" }; \
	for "_i" from 1 to 3 do { _obj addItemToUniform "cse_packing_bandage" }; \
	for "_i" from 1 to 3 do { _obj addItemToUniform "cse_quikclot" }; \
	for "_i" from 1 to 2 do { _obj addItemToUniform "cse_bandageElastic" }; \
	_obj addItemToUniform "cse_morphine";

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "LOGISTICS TEAMLEADER") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "b_itemGPS_FT";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "B_UavTerminal";
	this addWeapon "Binocular";
	this addHeadgear "H_Cap_headphones";
	this addUniform "U_I_G_Story_Protagonist_F";
	this addVest "V_Rangemaster_belt";
	this addBackpack "tf_rt1523g_black";
	for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToUniform "16Rnd_9x21_Mag";
	this addItemToBackpack "Toolkit";
	this addWeapon "arifle_MXC_Black_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellRed" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellGreen" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellOrange" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellBlue" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};
if (_class == "LOGISTICIAN") exitWith {
	removeAllWeapons this;
	removeAllItems this;
	removeAllAssignedItems this;
	removeUniform this;
	removeVest this;
	removeBackpack this;
	removeHeadgear this;
	removeGoggles this;
	this addWeapon "NVGoggles";
	this addWeapon "ItemCompass";
	this addWeapon "ItemMap";
	this addWeapon "ItemGPS";
	this addWeapon "tf_anprc152";
	this addWeapon "ItemWatch";
	this addWeapon "B_UavTerminal";
	this addWeapon "Binocular";
	this addHeadgear "H_Cap_headphones";
	this addUniform "U_I_G_Story_Protagonist_F";
	this addVest "V_Rangemaster_belt";
	this addBackpack "B_AssaultPack_blk";for "_i" from 1 to 4 do { this addItemToUniform "30Rnd_65x39_caseless_mag" };
	this addItemToUniform "16Rnd_9x21_Mag";
	this addItemToBackpack "Toolkit";
	this addWeapon "arifle_MXC_Black_F";
	this addWeapon "hgun_P07_F";
	this addPrimaryWeaponItem "optic_Aco";
	for "_i" from 1 to 2 do { this addItemToUniform "SmokeShellRed" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellGreen" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellOrange" };
	for "_i" from 1 to 2 do { this addItemToVest "SmokeShellBlue" };

	[this,false] call CSE_fnc_setMedicRole_CMS;
	this setVariable ["cse_enabled_AdvancedBallistics", false, true];
};